// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    CreateTodoForm: typeof import('./src/components/CreateTodoForm.vue')['default']
    CustomModal: typeof import('./src/components/modals/CustomModal.vue')['default']
    DefaultTodoList: typeof import('./src/components/DefaultTodoList.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Todo: typeof import('./src/components/Todo.vue')['default']
    TodoList: typeof import('./src/components/TodoList.vue')['default']
  }
}
