version: "3.8"

networks:
  laravel:

services:
  nginx:
    image: nginx:1.22-alpine
    ports:
      - ${BACKEND_PORT}:80
    depends_on:
      - php
    volumes:
      - ${BACKEND_PATH}:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - laravel
  php:
    build: 
      context: .
      dockerfile: dockerfiles/php/Dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    volumes:
      - ${BACKEND_PATH}:/var/www/html
    networks:
      - laravel
  websockets:
    build: 
      context: .
      dockerfile: dockerfiles/php/Dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    ports:
      - 6001:6001
    volumes:
      - ${BACKEND_PATH}:/var/www/html
    networks:
      - laravel
    command: php artisan websockets:serve
  composer:
    build:
      context: .
      dockerfile: dockerfiles/composer/Dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    volumes:
      - ${BACKEND_PATH}:/var/www/html
    working_dir: /var/www/html
    networks:
      - laravel
  node_backend:
    image: node:16-alpine3.15
    volumes:
      - ${BACKEND_PATH}:/var/www/html
    working_dir: /var/www/html
    networks:
      - laravel
  frontend:
    build:
      context: .
      dockerfile: dockerfiles/frontend/Dockerfile
    volumes:
      - ${FRONTEND_PATH}:/var/www/html
    working_dir: /var/www/html
    networks:
      - laravel
    command: http-server dist
    ports:
      - ${FRONTEND_PORT}:8080
  mysql:
    image: mysql:5.7.22
    ports:
      - ${MYSQL_PORT}:3306
    volumes:
      - ./database_data/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=laravel
    networks:
      - laravel